export enum AUTH_CONTSTANTS {
  PASSWORD_HASH_ROUND = 'PASSWORD_HASH_ROUND',
  JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET',
  JWT_ACCESS_TOKEN_EXPIRE_TIME = 'JWT_ACCESS_TOKEN_EXPIRE_TIME',
  JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET',
  JWT_REFRESH_TOKEN_EXPIRE_TIME = 'JWT_REFRESH_TOKEN_EXPIRE_TIME',
}
